blueprint:
  name: Z2M - ZG-101Z/D Dial Switch
  description: >
    Define actions your ZG-101Z/D Dial Switch switch using zigbee2mqtt.
    For your button entity, choose the right sensor with your button name.
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic for device updates
      description: MQTT topic for Philips Hue Tap dial switch. e.g. "zigbee2mqtt/Switch Music/action"
    operating_mode:
      name: ZG-101Z/D Dial Switch Operating Mode Select Entity
      description: the selector of the current operator mode. It switches when you triple press, which we'll facilitate as pattern
      selector:
        entity:
          domain: select
    # Short Press
    remote_button_short_press:
      name: Button Short Press
      description: Action to run on button short press
      default: []
      selector:
        action:
    # Long Press
    remote_button_long_press:
      name: Button Long Press
      description: Action to run on button long press
      default: []
      selector:
        action:
    # Double Press
    remote_button_double_press:
      name: Button double Press
      description: Action to run on button double press
      default: []
      selector:
        action:
    # Triple Press
    remote_button_triple_press:
      name: Button Triple Press
      description: Action to run on button triple press
      default: []
      selector:
        action:
    # Dial rotate left
    remote_dial_rotate_left:
      name: Dial rotate left step
      description: Action to run on dial rotate left step
      default: []
      selector:
        action:
    # Dial rotate right
    remote_dial_rotate_right:
      name: Dial rotate right step
      description: Action to run on dial rotate right step
      default: []
      selector:
        action:

mode: restart
max_exceeded: silent

# Each option is explicitly defined as a trigger because sensor reports empty values as well.
# Not defining explicit triggers causes the automation to show up in the log multiple times per button press.
triggers:
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: "single"
    value_template: "{{ value_json.action }}"
    id: "single"
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: "double"
    value_template: "{{ value_json.action }}"
    id: "double"
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: "hold"
    value_template: "{{ value_json.action }}"
    id: "hold"
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: "rotate_left"
    value_template: "{{ value_json.action }}"
    id: "rotate_left"
  - trigger: mqtt
    topic: !input mqtt_topic
    payload: "rotate_right"
    value_template: "{{ value_json.action }}"
    id: "rotate_right"
  - trigger: state
    entity_id: !input operating_mode
    from: "command"
    to: "event"
  - trigger: state
    entity_id: !input operating_mode
    from: "event"
    to: "command"
actions:
  - variables:
      command: "{{ trigger.to_state.state }}"

  - choose:
      - conditions:
          - condition: trigger
            id: "single"
        sequence: !input remote_button_short_press

      - conditions:
          - condition: trigger
            id: "double"
        sequence: !input remote_button_double_press

      - conditions:
          - condition: trigger
            id: "hold"
        sequence: !input remote_button_long_press

      - conditions:
          - condition: trigger
            id: "rotate_left"
        sequence: !input remote_dial_rotate_left

      - conditions:
          - condition: trigger
            id: "rotate_right"
        sequence: !input remote_dial_rotate_right

      - conditions:
          - or:
              - "{{ command == 'command' }}"
              - "{{ command == 'event' }}"
        sequence: !input remote_button_triple_press
